version: '1.0.{build}'
branches:
  only:
  - master
skip_tags: true
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
init:
  git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./GP.Microservices.Users.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./GP.Microservices.Users.csproj 
artifacts:
  - path: './bin/Debug/netcoreapp.20/publish'
  - name: GP.Microservices.Users
  - type: WebDeployPackage
deploy: off