version: '3.4'

services:
  gp.microservices.api:
    image: gpasnik/microservices-api
    build:
      context: GP.Microservices.Api
      dockerfile: ./Dockerfile
    ports:
      - "10000:80"
    links:
      - "rabbitmq:rabbit"
      - "gp.microservices.users:users"
      - "gp.microservices.remarks:remarks"
      - "gp.microservices.statistics:statistics"
      - "gp.microservices.storage:storage"
    depends_on:
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  gp.microservices.users:
    image: gpasnik/microservices-users
    build:
      context: GP.Microservices.Users
      dockerfile: ./Dockerfile
    hostname: users
    ports:
      - "10001:80"
    links:
      - "rabbitmq:rabbit"
      - "sqlserver:db"
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  gp.microservices.remarks:
    image: gpasnik/microservices-remarks
    build:
      context: GP.Microservices.Remarks
      dockerfile: ./Dockerfile
    ports:
      - "10002:80"
    links:
      - "rabbitmq:rabbit"
      - "sqlserver:db"
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  gp.microservices.statistics:
    image: gpasnik/microservices-statistics
    build:
      context: GP.Microservices.Statistics
      dockerfile: ./Dockerfile
    ports:
      - "10003:80"
    links:
      - "rabbitmq:rabbit"
      - "sqlserver:db"
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT : Development

  gp.microservices.storage:
    image: gpasnik/microservices-storage
    build:
      context: GP.Microservices.Storage
      dockerfile: ./Dockerfile
    ports:
      - "10004:80"
    links:
      - "rabbitmq:rabbit"
      - "sqlserver:db"
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  sqlserver:
    image: "microsoft/mssql-server-linux:2017-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123QWEasd"
    ports:
      - "5433:1433"