---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "microservices-remarks"
  namespace: "default"
  labels:
    app: "microservices-remarks"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "microservices-remarks"
  template:
    metadata:
      labels:
        app: "microservices-remarks"
    spec:
      containers:
      - name: "microservices-remarks"
        image: "gpasnik/microservices-remarks:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_RabbitMq__Host
          value: "rabbitmq://10.132.0.11:5672"
        - name: APP_RabbitMq__User
          value: "admin"
        - name: APP_RabbitMq__Password
          value: "password"
        - name: APP_ConnectionStrings__RemarksDb
          value: "Server=10.132.0.10,1433;Database=GP.Microservices.Remarks;User=sa;Password=123QWEasd;MultipleActiveResultSets=true;"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "microservices-remarks-hpa"
  namespace: "default"
  labels:
    app: "microservices-remarks"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "microservices-remarks"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "microservices-remarks-service"
  namespace: "default"
  labels:
    app: "microservices-remarks"
spec:
  ports:
  - protocol: "TCP"
    port: 10002
    targetPort: 80
  selector:
    app: "microservices-remarks"
  type: "ClusterIP"

