--- 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata: 
  name: deployment-manager-binding
  namespace: gp
roleRef: 
  apiGroup: ""
  kind: Role
  name: deployment-manager
subjects: 
  - 
    apiGroup: ""
    kind: User
    name: user
