---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "microservices-api"
  namespace: "default"
  labels:
    app: "microservices-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "microservices-api"
  template:
    metadata:
      labels:
        app: "microservices-api"
    spec:
      containers:
      - name: "microservices-api"
        image: "gpasnik/microservices-api:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_RabbitMq__Host
          value: "rabbitmq://10.132.0.11:5672"
        - name: APP_RabbitMq__User
          value: "admin"
        - name: APP_RabbitMq__Password
          value: "password"
        - name: APP_RemarkServiceClient__ApiUrl
          value: "http://microservices-remarks:80/api"
        - name: APP_UserServiceClient__ApiUrl
          value: "http://microservices-users:80/api"
        - name: APP_StorageServiceClient__ApiUrl
          value: "http://microservices-storage:80/api"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "microservices-api-hpa"
  namespace: "default"
  labels:
    app: "microservices-api"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "microservices-api"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
