---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "microservices-storage"
  namespace: "default"
  labels:
    app: "microservices-storage"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "microservices-storage"
  template:
    metadata:
      labels:
        app: "microservices-storage"
    spec:
      containers:
      - name: "microservices-storage"
        image: "gpasnik/microservices-storage:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_RabbitMq__Host
          value: "rabbitmq://10.132.0.11:5672"
        - name: APP_RabbitMq__User
          value: "admin"
        - name: APP_RabbitMq__Password
          value: "password"
        - name: APP_RemarkServiceClient__ApiUrl
          value: "http://microservices-remarks-service/api"
        - name: APP_UserServiceClient__ApiUrl
          value: "http://microservices-users-service/api"
        - name: APP_StorageServiceClient__ApiUrl
          value: "http://microservices-storage-service/api"
        - name: APP_MongoDb__ConnectionString
          value: "mongodb://root:example@10.132.0.12:27017"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "microservices-storage-hpa"
  namespace: "default"
  labels:
    app: "microservices-storage"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "microservices-storage"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "microservices-storage-service"
  namespace: "default"
  labels:
    app: "microservices-storage"
spec:
  ports:
  - protocol: "TCP"
    port: 10003
    targetPort: 80
  selector:
    app: "microservices-storage"
  type: "ClusterIP"

