--- 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata: 
  name: deployment-manager
  namespace: gp
rules: 
  - 
    apiGroups: 
      - ""
      - extensions
      - apps
    resources: 
      - deployments
      - replicasets
      - pods
    verbs: 
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
