---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "microservices-statistics"
  namespace: "default"
  labels:
    app: "microservices-statistics"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "microservices-statistics"
  template:
    metadata:
      labels:
        app: "microservices-statistics"
    spec:
      containers:
      - name: "microservices-statistics"
        image: "gpasnik/microservices-statistics:latest"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "microservices-statistics-hpa"
  namespace: "default"
  labels:
    app: "microservices-statistics"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "microservices-statistics"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "microservices-statistics-service"
  namespace: "default"
  labels:
    app: "microservices-statistics"
spec:
  ports:
  - protocol: "TCP"
    port: 10004
    targetPort: 80
  selector:
    app: "microservices-statistics"
  type: "ClusterIP"

